#include <odyssey/protocol/get_config.hpp>
#include <odyssey/protocol/config.hpp>
#include <odyssey/protocol/asset.hpp>
#include <odyssey/protocol/types.hpp>
#include <odyssey/protocol/version.hpp>

namespace odyssey { namespace protocol {

fc::variant_object get_config()
{
   fc::mutable_variant_object result;

#ifdef IS_TEST_NET
   result[ "IS_TEST_NET" ] = true;
#else
   result[ "IS_TEST_NET" ] = false;
#endif

   result["SBD_SYMBOL"] = SBD_SYMBOL;
   result["ODYSSEY_100_PERCENT"] = ODYSSEY_100_PERCENT;
   result["ODYSSEY_1_PERCENT"] = ODYSSEY_1_PERCENT;
   result["ODYSSEY_1_TENTH_PERCENT"] = ODYSSEY_1_TENTH_PERCENT;
   result["ODYSSEY_ACCOUNT_RECOVERY_REQUEST_EXPIRATION_PERIOD"] = ODYSSEY_ACCOUNT_RECOVERY_REQUEST_EXPIRATION_PERIOD;
   result["ODYSSEY_ACTIVE_CHALLENGE_COOLDOWN"] = ODYSSEY_ACTIVE_CHALLENGE_COOLDOWN;
   result["ODYSSEY_ACTIVE_CHALLENGE_FEE"] = ODYSSEY_ACTIVE_CHALLENGE_FEE;
   result["ODYSSEY_ADDRESS_PREFIX"] = ODYSSEY_ADDRESS_PREFIX;
   result["ODYSSEY_APR_PERCENT_MULTIPLY_PER_BLOCK"] = ODYSSEY_APR_PERCENT_MULTIPLY_PER_BLOCK;
   result["ODYSSEY_APR_PERCENT_MULTIPLY_PER_HOUR"] = ODYSSEY_APR_PERCENT_MULTIPLY_PER_HOUR;
   result["ODYSSEY_APR_PERCENT_MULTIPLY_PER_ROUND"] = ODYSSEY_APR_PERCENT_MULTIPLY_PER_ROUND;
   result["ODYSSEY_APR_PERCENT_SHIFT_PER_BLOCK"] = ODYSSEY_APR_PERCENT_SHIFT_PER_BLOCK;
   result["ODYSSEY_APR_PERCENT_SHIFT_PER_HOUR"] = ODYSSEY_APR_PERCENT_SHIFT_PER_HOUR;
   result["ODYSSEY_APR_PERCENT_SHIFT_PER_ROUND"] = ODYSSEY_APR_PERCENT_SHIFT_PER_ROUND;
   result["ODYSSEY_BANDWIDTH_AVERAGE_WINDOW_SECONDS"] = ODYSSEY_BANDWIDTH_AVERAGE_WINDOW_SECONDS;
   result["ODYSSEY_BANDWIDTH_PRECISION"] = ODYSSEY_BANDWIDTH_PRECISION;
   result["ODYSSEY_BLOCKCHAIN_PRECISION"] = ODYSSEY_BLOCKCHAIN_PRECISION;
   result["ODYSSEY_BLOCKCHAIN_PRECISION_DIGITS"] = ODYSSEY_BLOCKCHAIN_PRECISION_DIGITS;
   result["ODYSSEY_BLOCKCHAIN_HARDFORK_VERSION"] = ODYSSEY_BLOCKCHAIN_HARDFORK_VERSION;
   result["ODYSSEY_BLOCKCHAIN_VERSION"] = ODYSSEY_BLOCKCHAIN_VERSION;
   result["ODYSSEY_BLOCK_INTERVAL"] = ODYSSEY_BLOCK_INTERVAL;
   result["ODYSSEY_BLOCKS_PER_DAY"] = ODYSSEY_BLOCKS_PER_DAY;
   result["ODYSSEY_BLOCKS_PER_HOUR"] = ODYSSEY_BLOCKS_PER_HOUR;
   result["ODYSSEY_BLOCKS_PER_YEAR"] = ODYSSEY_BLOCKS_PER_YEAR;
   result["ODYSSEY_CASHOUT_WINDOW_SECONDS"] = ODYSSEY_CASHOUT_WINDOW_SECONDS;
   result["ODYSSEY_CASHOUT_WINDOW_SECONDS_PRE_HF12"] = ODYSSEY_CASHOUT_WINDOW_SECONDS_PRE_HF12;
   result["ODYSSEY_CASHOUT_WINDOW_SECONDS_PRE_HF17"] = ODYSSEY_CASHOUT_WINDOW_SECONDS_PRE_HF17;
   result["ODYSSEY_CHAIN_ID"] = ODYSSEY_CHAIN_ID;
   result["ODYSSEY_COMMENT_REWARD_FUND_NAME"] = ODYSSEY_COMMENT_REWARD_FUND_NAME;
   result["ODYSSEY_CONTENT_APR_PERCENT"] = ODYSSEY_CONTENT_APR_PERCENT;
   result["ODYSSEY_CONTENT_CONSTANT_HF0"] = ODYSSEY_CONTENT_CONSTANT_HF0;
   result["ODYSSEY_CONTENT_REWARD_PERCENT"] = ODYSSEY_CONTENT_REWARD_PERCENT;
   result["ODYSSEY_CONVERSION_DELAY"] = ODYSSEY_CONVERSION_DELAY;
   result["ODYSSEY_CONVERSION_DELAY_PRE_HF_16"] = ODYSSEY_CONVERSION_DELAY_PRE_HF_16;
   result["ODYSSEY_CREATE_ACCOUNT_DELEGATION_RATIO"] = ODYSSEY_CREATE_ACCOUNT_DELEGATION_RATIO;
   result["ODYSSEY_CREATE_ACCOUNT_DELEGATION_TIME"] = ODYSSEY_CREATE_ACCOUNT_DELEGATION_TIME;
   result["ODYSSEY_CREATE_ACCOUNT_WITH_ODYSSEY_MODIFIER"] = ODYSSEY_CREATE_ACCOUNT_WITH_ODYSSEY_MODIFIER;
   result["ODYSSEY_CURATE_APR_PERCENT"] = ODYSSEY_CURATE_APR_PERCENT;
   result["ODYSSEY_DEFAULT_SBD_INTEREST_RATE"] = ODYSSEY_DEFAULT_SBD_INTEREST_RATE;
   result["ODYSSEY_EQUIHASH_K"] = ODYSSEY_EQUIHASH_K;
   result["ODYSSEY_EQUIHASH_N"] = ODYSSEY_EQUIHASH_N;
   result["ODYSSEY_FEED_HISTORY_WINDOW"] = ODYSSEY_FEED_HISTORY_WINDOW;
   result["ODYSSEY_FEED_HISTORY_WINDOW_PRE_HF_16"] = ODYSSEY_FEED_HISTORY_WINDOW_PRE_HF_16;
   result["ODYSSEY_FEED_INTERVAL_BLOCKS"] = ODYSSEY_FEED_INTERVAL_BLOCKS;
   result["ODYSSEY_FREE_TRANSACTIONS_WITH_NEW_ACCOUNT"] = ODYSSEY_FREE_TRANSACTIONS_WITH_NEW_ACCOUNT;
   result["ODYSSEY_GENESIS_TIME"] = ODYSSEY_GENESIS_TIME;
   result["ODYSSEY_HARDFORK_REQUIRED_WITNESSES"] = ODYSSEY_HARDFORK_REQUIRED_WITNESSES;
   result["ODYSSEY_INFLATION_NARROWING_PERIOD"] = ODYSSEY_INFLATION_NARROWING_PERIOD;
   result["ODYSSEY_INFLATION_RATE_START_PERCENT"] = ODYSSEY_INFLATION_RATE_START_PERCENT;
   result["ODYSSEY_INFLATION_RATE_STOP_PERCENT"] = ODYSSEY_INFLATION_RATE_STOP_PERCENT;
   result["ODYSSEY_INIT_MINER_NAME"] = ODYSSEY_INIT_MINER_NAME;
   result["ODYSSEY_INIT_PUBLIC_KEY_STR"] = ODYSSEY_INIT_PUBLIC_KEY_STR;
#if 0
   // do not expose private key, period.
   // we need this line present but inactivated so CI check for all constants in config.hpp doesn't complain.
   result["ODYSSEY_INIT_PRIVATE_KEY"] = ODYSSEY_INIT_PRIVATE_KEY;
#endif
   result["ODYSSEY_INIT_SUPPLY"] = ODYSSEY_INIT_SUPPLY;
   result["ODYSSEY_INIT_TIME"] = ODYSSEY_INIT_TIME;
   result["ODYSSEY_IRREVERSIBLE_THRESHOLD"] = ODYSSEY_IRREVERSIBLE_THRESHOLD;
   result["ODYSSEY_LIQUIDITY_APR_PERCENT"] = ODYSSEY_LIQUIDITY_APR_PERCENT;
   result["ODYSSEY_LIQUIDITY_REWARD_BLOCKS"] = ODYSSEY_LIQUIDITY_REWARD_BLOCKS;
   result["ODYSSEY_LIQUIDITY_REWARD_PERIOD_SEC"] = ODYSSEY_LIQUIDITY_REWARD_PERIOD_SEC;
   result["ODYSSEY_LIQUIDITY_TIMEOUT_SEC"] = ODYSSEY_LIQUIDITY_TIMEOUT_SEC;
   result["ODYSSEY_MAX_ACCOUNT_NAME_LENGTH"] = ODYSSEY_MAX_ACCOUNT_NAME_LENGTH;
   result["ODYSSEY_MAX_ACCOUNT_WITNESS_VOTES"] = ODYSSEY_MAX_ACCOUNT_WITNESS_VOTES;
   result["ODYSSEY_MAX_ASSET_WHITELIST_AUTHORITIES"] = ODYSSEY_MAX_ASSET_WHITELIST_AUTHORITIES;
   result["ODYSSEY_MAX_AUTHORITY_MEMBERSHIP"] = ODYSSEY_MAX_AUTHORITY_MEMBERSHIP;
   result["ODYSSEY_MAX_BLOCK_SIZE"] = ODYSSEY_MAX_BLOCK_SIZE;
   result["ODYSSEY_MAX_CASHOUT_WINDOW_SECONDS"] = ODYSSEY_MAX_CASHOUT_WINDOW_SECONDS;
   result["ODYSSEY_MAX_COMMENT_DEPTH"] = ODYSSEY_MAX_COMMENT_DEPTH;
   result["ODYSSEY_MAX_COMMENT_DEPTH_PRE_HF17"] = ODYSSEY_MAX_COMMENT_DEPTH_PRE_HF17;
   result["ODYSSEY_MAX_FEED_AGE_SECONDS"] = ODYSSEY_MAX_FEED_AGE_SECONDS;
   result["ODYSSEY_MAX_INSTANCE_ID"] = ODYSSEY_MAX_INSTANCE_ID;
   result["ODYSSEY_MAX_MEMO_SIZE"] = ODYSSEY_MAX_MEMO_SIZE;
   result["ODYSSEY_MAX_WITNESSES"] = ODYSSEY_MAX_WITNESSES;
   result["ODYSSEY_MAX_MINER_WITNESSES_HF0"] = ODYSSEY_MAX_MINER_WITNESSES_HF0;
   result["ODYSSEY_MAX_MINER_WITNESSES_HF17"] = ODYSSEY_MAX_MINER_WITNESSES_HF17;
   result["ODYSSEY_MAX_PERMLINK_LENGTH"] = ODYSSEY_MAX_PERMLINK_LENGTH;
   result["ODYSSEY_MAX_PROXY_RECURSION_DEPTH"] = ODYSSEY_MAX_PROXY_RECURSION_DEPTH;
   result["ODYSSEY_MAX_RATION_DECAY_RATE"] = ODYSSEY_MAX_RATION_DECAY_RATE;
   result["ODYSSEY_MAX_RESERVE_RATIO"] = ODYSSEY_MAX_RESERVE_RATIO;
   result["ODYSSEY_MAX_RUNNER_WITNESSES_HF0"] = ODYSSEY_MAX_RUNNER_WITNESSES_HF0;
   result["ODYSSEY_MAX_RUNNER_WITNESSES_HF17"] = ODYSSEY_MAX_RUNNER_WITNESSES_HF17;
   result["ODYSSEY_MAX_SHARE_SUPPLY"] = ODYSSEY_MAX_SHARE_SUPPLY;
   result["ODYSSEY_MAX_SIG_CHECK_DEPTH"] = ODYSSEY_MAX_SIG_CHECK_DEPTH;
   result["ODYSSEY_MAX_TIME_UNTIL_EXPIRATION"] = ODYSSEY_MAX_TIME_UNTIL_EXPIRATION;
   result["ODYSSEY_MAX_TRANSACTION_SIZE"] = ODYSSEY_MAX_TRANSACTION_SIZE;
   result["ODYSSEY_MAX_UNDO_HISTORY"] = ODYSSEY_MAX_UNDO_HISTORY;
   result["ODYSSEY_MAX_URL_LENGTH"] = ODYSSEY_MAX_URL_LENGTH;
   result["ODYSSEY_MAX_VOTE_CHANGES"] = ODYSSEY_MAX_VOTE_CHANGES;
   result["ODYSSEY_MAX_VOTED_WITNESSES_HF0"] = ODYSSEY_MAX_VOTED_WITNESSES_HF0;
   result["ODYSSEY_MAX_VOTED_WITNESSES_HF17"] = ODYSSEY_MAX_VOTED_WITNESSES_HF17;
   result["ODYSSEY_MAX_WITHDRAW_ROUTES"] = ODYSSEY_MAX_WITHDRAW_ROUTES;
   result["ODYSSEY_MAX_WITNESS_URL_LENGTH"] = ODYSSEY_MAX_WITNESS_URL_LENGTH;
   result["ODYSSEY_MIN_ACCOUNT_CREATION_FEE"] = ODYSSEY_MIN_ACCOUNT_CREATION_FEE;
   result["ODYSSEY_MIN_ACCOUNT_NAME_LENGTH"] = ODYSSEY_MIN_ACCOUNT_NAME_LENGTH;
   result["ODYSSEY_MIN_BLOCK_SIZE"] = ODYSSEY_MIN_BLOCK_SIZE;
   result["ODYSSEY_MIN_BLOCK_SIZE_LIMIT"] = ODYSSEY_MIN_BLOCK_SIZE_LIMIT;
   result["ODYSSEY_MIN_CONTENT_REWARD"] = ODYSSEY_MIN_CONTENT_REWARD;
   result["ODYSSEY_MIN_CURATE_REWARD"] = ODYSSEY_MIN_CURATE_REWARD;
   result["ODYSSEY_MIN_PERMLINK_LENGTH"] = ODYSSEY_MIN_PERMLINK_LENGTH;
   result["ODYSSEY_MIN_REPLY_INTERVAL"] = ODYSSEY_MIN_REPLY_INTERVAL;
   result["ODYSSEY_MIN_ROOT_COMMENT_INTERVAL"] = ODYSSEY_MIN_ROOT_COMMENT_INTERVAL;
   result["ODYSSEY_MIN_VOTE_INTERVAL_SEC"] = ODYSSEY_MIN_VOTE_INTERVAL_SEC;
   result["ODYSSEY_MINER_ACCOUNT"] = ODYSSEY_MINER_ACCOUNT;
   result["ODYSSEY_MINER_PAY_PERCENT"] = ODYSSEY_MINER_PAY_PERCENT;
   result["ODYSSEY_MIN_FEEDS"] = ODYSSEY_MIN_FEEDS;
   result["ODYSSEY_MINING_REWARD"] = ODYSSEY_MINING_REWARD;
   result["ODYSSEY_MINING_TIME"] = ODYSSEY_MINING_TIME;
   result["ODYSSEY_MIN_LIQUIDITY_REWARD"] = ODYSSEY_MIN_LIQUIDITY_REWARD;
   result["ODYSSEY_MIN_LIQUIDITY_REWARD_PERIOD_SEC"] = ODYSSEY_MIN_LIQUIDITY_REWARD_PERIOD_SEC;
   result["ODYSSEY_MIN_PAYOUT_SBD"] = ODYSSEY_MIN_PAYOUT_SBD;
   result["ODYSSEY_MIN_POW_REWARD"] = ODYSSEY_MIN_POW_REWARD;
   result["ODYSSEY_MIN_PRODUCER_REWARD"] = ODYSSEY_MIN_PRODUCER_REWARD;
   result["ODYSSEY_MIN_RATION"] = ODYSSEY_MIN_RATION;
   result["ODYSSEY_MIN_TRANSACTION_EXPIRATION_LIMIT"] = ODYSSEY_MIN_TRANSACTION_EXPIRATION_LIMIT;
   result["ODYSSEY_MIN_TRANSACTION_SIZE_LIMIT"] = ODYSSEY_MIN_TRANSACTION_SIZE_LIMIT;
   result["ODYSSEY_MIN_UNDO_HISTORY"] = ODYSSEY_MIN_UNDO_HISTORY;
   result["ODYSSEY_NULL_ACCOUNT"] = ODYSSEY_NULL_ACCOUNT;
   result["ODYSSEY_NUM_INIT_MINERS"] = ODYSSEY_NUM_INIT_MINERS;
   result["ODYSSEY_ORIGINAL_MIN_ACCOUNT_CREATION_FEE"] = ODYSSEY_ORIGINAL_MIN_ACCOUNT_CREATION_FEE;
   result["ODYSSEY_OWNER_AUTH_HISTORY_TRACKING_START_BLOCK_NUM"] = ODYSSEY_OWNER_AUTH_HISTORY_TRACKING_START_BLOCK_NUM;
   result["ODYSSEY_OWNER_AUTH_RECOVERY_PERIOD"] = ODYSSEY_OWNER_AUTH_RECOVERY_PERIOD;
   result["ODYSSEY_OWNER_CHALLENGE_COOLDOWN"] = ODYSSEY_OWNER_CHALLENGE_COOLDOWN;
   result["ODYSSEY_OWNER_CHALLENGE_FEE"] = ODYSSEY_OWNER_CHALLENGE_FEE;
   result["ODYSSEY_OWNER_UPDATE_LIMIT"] = ODYSSEY_OWNER_UPDATE_LIMIT;
   result["ODYSSEY_POST_AVERAGE_WINDOW"] = ODYSSEY_POST_AVERAGE_WINDOW;
   result["ODYSSEY_POST_MAX_BANDWIDTH"] = ODYSSEY_POST_MAX_BANDWIDTH;
   result["ODYSSEY_POST_REWARD_FUND_NAME"] = ODYSSEY_POST_REWARD_FUND_NAME;
   result["ODYSSEY_POST_WEIGHT_CONSTANT"] = ODYSSEY_POST_WEIGHT_CONSTANT;
   result["ODYSSEY_POW_APR_PERCENT"] = ODYSSEY_POW_APR_PERCENT;
   result["ODYSSEY_PRODUCER_APR_PERCENT"] = ODYSSEY_PRODUCER_APR_PERCENT;
   result["ODYSSEY_PROXY_TO_SELF_ACCOUNT"] = ODYSSEY_PROXY_TO_SELF_ACCOUNT;
   result["ODYSSEY_SBD_INTEREST_COMPOUND_INTERVAL_SEC"] = ODYSSEY_SBD_INTEREST_COMPOUND_INTERVAL_SEC;
   result["ODYSSEY_SECONDS_PER_YEAR"] = ODYSSEY_SECONDS_PER_YEAR;
   result["ODYSSEY_RECENT_RSHARES_DECAY_RATE_HF19"] = ODYSSEY_RECENT_RSHARES_DECAY_RATE_HF19;
   result["ODYSSEY_RECENT_RSHARES_DECAY_RATE_HF17"] = ODYSSEY_RECENT_RSHARES_DECAY_RATE_HF17;
   result["ODYSSEY_REVERSE_AUCTION_WINDOW_SECONDS"] = ODYSSEY_REVERSE_AUCTION_WINDOW_SECONDS;
   result["ODYSSEY_ROOT_POST_PARENT"] = ODYSSEY_ROOT_POST_PARENT;
   result["ODYSSEY_SAVINGS_WITHDRAW_REQUEST_LIMIT"] = ODYSSEY_SAVINGS_WITHDRAW_REQUEST_LIMIT;
   result["ODYSSEY_SAVINGS_WITHDRAW_TIME"] = ODYSSEY_SAVINGS_WITHDRAW_TIME;
   result["ODYSSEY_SBD_START_PERCENT"] = ODYSSEY_SBD_START_PERCENT;
   result["ODYSSEY_SBD_STOP_PERCENT"] = ODYSSEY_SBD_STOP_PERCENT;
   result["ODYSSEY_SECOND_CASHOUT_WINDOW"] = ODYSSEY_SECOND_CASHOUT_WINDOW;
   result["ODYSSEY_SOFT_MAX_COMMENT_DEPTH"] = ODYSSEY_SOFT_MAX_COMMENT_DEPTH;
   result["ODYSSEY_START_MINER_VOTING_BLOCK"] = ODYSSEY_START_MINER_VOTING_BLOCK;
   result["ODYSSEY_START_VESTING_BLOCK"] = ODYSSEY_START_VESTING_BLOCK;
   result["ODYSSEY_SYMBOL"] = ODYSSEY_SYMBOL;
   result["ODYSSEY_TEMP_ACCOUNT"] = ODYSSEY_TEMP_ACCOUNT;
   result["ODYSSEY_UPVOTE_LOCKOUT_HF7"] = ODYSSEY_UPVOTE_LOCKOUT_HF7;
   result["ODYSSEY_UPVOTE_LOCKOUT_HF17"] = ODYSSEY_UPVOTE_LOCKOUT_HF17;
   result["ODYSSEY_VESTING_FUND_PERCENT"] = ODYSSEY_VESTING_FUND_PERCENT;
   result["ODYSSEY_VESTING_WITHDRAW_INTERVALS"] = ODYSSEY_VESTING_WITHDRAW_INTERVALS;
   result["ODYSSEY_VESTING_WITHDRAW_INTERVALS_PRE_HF_16"] = ODYSSEY_VESTING_WITHDRAW_INTERVALS_PRE_HF_16;
   result["ODYSSEY_VESTING_WITHDRAW_INTERVAL_SECONDS"] = ODYSSEY_VESTING_WITHDRAW_INTERVAL_SECONDS;
   result["ODYSSEY_VOTE_CHANGE_LOCKOUT_PERIOD"] = ODYSSEY_VOTE_CHANGE_LOCKOUT_PERIOD;
   result["ODYSSEY_VOTE_DUST_THRESHOLD"] = ODYSSEY_VOTE_DUST_THRESHOLD;
   result["ODYSSEY_VOTE_REGENERATION_SECONDS"] = ODYSSEY_VOTE_REGENERATION_SECONDS;
   result["ODYSSEY_SYMBOL"] = ODYSSEY_SYMBOL;
   result["STMD_SYMBOL"] = STMD_SYMBOL;
   result["VESTS_SYMBOL"] = VESTS_SYMBOL;
   result["VIRTUAL_SCHEDULE_LAP_LENGTH"] = VIRTUAL_SCHEDULE_LAP_LENGTH;
   result["VIRTUAL_SCHEDULE_LAP_LENGTH2"] = VIRTUAL_SCHEDULE_LAP_LENGTH2;

   return result;
}

} } // odyssey::protocol
